### ISSUE TITLE
Information about file DATA_Acq.md 

### ISSUE THREAD

**Issue by mariaconcettavitale** [bgudenas/DeepLncRNA#5]
Hello .
In DATA_Acq.md when extracting the 14th field from metadata.tsv this field is empty. Why?

Later, when I run the awk command 'BEGIN {FS = "\ t"} ($ 14! = "")' Metadata.tsv | cut -f 42> Subcell_DL_urls, in Subcell_DL_urls there is only one line and the command xargs -n 1 curl -O -L <../ Meta / Subcell_DL_urls it
fails

**Comment by bgudenas** [comment]
Hi Conny,

The referenced line
`awk 'BEGIN {FS="\t"} ($14 != "")' metadata.tsv  | cut -f 42 > Subcell_DL_urls`

Filters the ENCODE metadata file to only retain the RNA-seq samples which do not have an empty value in the 14th column (Subcellular fraction).

 If ENCODE has changed the column ordering of their metadata file, since this publication, this could cause the issue you are seeing. Please check the column headers of Metadata.tsv and find the subcellular fraction column if it is not 14 then change the value in the awk command to whatever the new column is.

**Comment by ConnyVitale** [comment]
Hi,
Thanks for your response. I have another questions.
How can I train the neural network to add prediction for cytoplasm and exosomes too?
